### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Sly777** [project-collins/grunt-csssplit#13]
Hi all,

I'm getting this error when i use csssplit. Details is below. Btw, it's first time i used grunt-csssplit. So it's latest version. I'm trying to use it because i have ie9 shitty limit error :)

Running "csssplit:prod" (csssplit) task
Verifying property csssplit.prod exists in config...OK
Files: ../../../assets/styles/app.css -> ../../../assets/styles
Options: suffix="_part_", maxSelectors=4095, maxPages=false
Reading ../../../assets/styles/app.css...OK
Warning: Maximum call stack size exceeded Use --force to continue.

**Comment by robotlovesyou** [comment]
It would be very helpful if you could try to isolate the code causing the issue and create a gist or similar so I can reproduce the error. This isn't behaviour I've seen from it before.

**Comment by Sly777** [comment]
hi @robotlovesyou , if you give email, i can send css file.

**Comment by robotlovesyou** [comment]
Well, since this is in use in production without showing this error, what I'd be looking for at minimum is a gruntfile and a css file which together reproduce the error. (The version of node/iojs you are using would also be helpful)

If you aren't comfortable pasting those into a gist then my email address is on my github profile page.

**Comment by robotlovesyou** [comment]
Closing this due to lack of response
